---
- name: restart php-resque
  service: name=php-resque enabled=yes state=restarted

- name: restart deploynaut-pipelines
  service: name=deploynaut-pipelines enabled=yes state=restarted

- name: restart apache
  service: name=apache2 enabled=yes state=restarted
