---
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: create www-data composer cache folder
  file: state=directory path=/var/www/.composer owner=www-data group=composer mode=2775

- name: install ruby and rediss
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby
    - redis-server

- name: install gem capistrano
  gem: name=capistrano version=2.15.5 state=present user_install=no

- name: install gem capistrano-multiconfig
  gem: name=capistrano-multiconfig version=0.0.4 state=present user_install=no

- name: install resque gem
  gem: name=resque state=present user_install=no

- name: setup the PHP Resque init script
  template: src=etc/init.d/php-resque dest=/etc/init.d/php-resque mode=0777

- name: set up deploynaut _ss_environment.php
  template: src=_ss_environment.php.j2 dest=/var/www/_ss_environment.php owner=www-data group=www-data mode=0666

- name: allow www-data to sudo to composer
  template: src=etc/sudoers.d/10_composer.j2 dest=/etc/sudoers.d/10_composer mode=0440

- name: create deploynaut web folders
  file: state=directory path=/var/www/{{ item }} owner=www-data group=composer mode=2775
  with_items:
    - git-clones
    - deploynaut-resources/envs
    - www-keys

- name: create ~www-data/.ssh
  file: state=directory path=/var/www/.ssh owner=www-data group=www-data mode=2750

- name: copy www ssh keys
  copy: src=www-keys/www_{{ item }} dest=/var/www/www-keys/{{ item }} mode=0600 owner=www-data group=www-data
  with_items:
    - id_rsa
    - id_rsa.pub


# Note this does not support key-based cloning - the repo has to be public.
- name: clone environments
  shell: if [ ! -d /var/www/git-clones/{{ item }} ]; then sudo -u www-data git clone --bare -q https://github.com/stojg/sandbox.dev.git /var/www/git-clones/{{ item }}; fi
  with_items:
  - ha
  - standard
